export const dadosPaginas = [
  {
    id: 0,
    nome: "Butherfree",
    imagem: "img/Pokemon 1.jpg",
    preco: 150.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 1,
    nome: "Meganium",
    imagem: "img/pokemon3.jpg",
    preco: 130.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 2,
    nome: "Gengar",
    imagem: "img/pokemon4.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 3,
    nome: "Bulbasaur",
    imagem: "img/Pokemon2.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 4,
    nome: "Gengar",
    imagem: "img/pokemon4.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 5,
    nome: "Bulbasaur",
    imagem: "img/Pokemon2.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 6,
    nome: "Wiglypuff",
    imagem: "img/pokemon5.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 7,
    nome: "Verdinho",
    imagem: "img/pokemon6.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 8,
    nome: "Butherfree",
    imagem: "img/Pokemon 1.jpg",
    preco: 120.0 + " Kwanzas",
    total: "",
  },
  {
    id: 9,
    nome: "Meganium",
    imagem: "img/pokemon3.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 10,
    nome: "Mewtwo",
    imagem: "img/pokemon6.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 11,
    nome: "Bulbasaur",
    imagem: "img/Pokemon2.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 12,
    nome: "Wiglypuff",
    imagem: "img/pokemon5.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 13,
    nome: "Meganium",
    imagem: "img/pokemon3.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 14,
    nome: "Gengar",
    imagem: "img/pokemon4.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 15,
    nome: "Bulbasaur",
    imagem: "img/Pokemon2.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 16,
    nome: "Butherfree",
    imagem: "img/Pokemon 1.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 17,
    nome: "Meganium",
    imagem: "img/pokemon3.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 18,
    nome: "Mewtwo",
    imagem: "img/pokemon6.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 19,
    nome: "Gengar",
    imagem: "img/pokemon4.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 20,
    nome: "Bulbasaur",
    imagem: "img/Pokemon2.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 21,
    nome: "Bulbasaur",
    imagem: "img/Pokemon2.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 22,
    nome: "Gengar",
    imagem: "img/pokemon4.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 23,
    nome: "Wiglypuff",
    imagem: "img/pokemon5.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 24,
    nome: "Butherfree",
    imagem: "img/Pokemon 1.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 25,
    nome: "Meganium",
    imagem: "img/pokemon3.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 26,
    nome: "Gengar",
    imagem: "img/pokemon4.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 27,
    nome: "Bulbasaur",
    imagem: "img/Pokemon2.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 28,
    nome: "Mewtwo",
    imagem: "img/pokemon6.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 29,
    nome: "Wiglypuff",
    imagem: "img/pokemon5.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 30,
    nome: "Gengar",
    imagem: "img/pokemon4.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
  {
    id: 31,
    nome: "Bulbasaur",
    imagem: "img/Pokemon2.jpg",
    preco: 120.0 + " Kwanzas",
    quantidade: "",
    total: "",
  },
];
