import initModal from './modules/modal.js';
import initPagin from './modules/paginacao.js';
import initModal1 from './modules/modal2.js';
import carrinho from './modules/pokemon.js';
import initAuth from './modules/auth.js';
initPagin();
initModal();
initModal1();
carrinho();
initAuth();
// const catalogoPrincipalElement = document.querySelector('.catalogoPrincipal');
// pokemon(catalogoPrincipalElement);
